
* relisp

Relisp is an [[https://www.gnu.org/software/emacs/][emacs]] package and minor-mode for refactoring Emacs-lisp code.
It may be expanded to support other LISP-forms like Common Lisp, Scheme and Clojure.

** Functionality

The following functions are either implemented or planned.

|------------------+-------------+------------------------------------------------------|
| Function         | Key-binding | Comment / Status                                     |
|------------------+-------------+------------------------------------------------------|
| Select sexp      | C-M-<SPC>   | Improved version of ~mark-sexp~.                     |
| Extract function | C-' C-x     | Implemented, but does not detect local symbol usage. |
| Rename symbol    | C-' C-r     | TODO                                                 |
| Inline symbol    | C-' C-i     | TODO                                                 |
|------------------+-------------+------------------------------------------------------|

** Installation

You can install currently only install relisp manually from this repo. If the codebase reaches a more mature
state, it may be published as a MELPA or Marmelade-package.

First clone the repo. The code has no other or external dependencies.

#+BEGIN_SRC sh
  mkdir -p ~/emacs-packages
  cd ~/emacs-packages
  git clone https://github.com/josteink/relisp.git
#+END_SRC

Add the following line to your ~.emacs~ or ~init.el~ (or wherever you stash things like this):

#+BEGIN_SRC emacs-lisp
  (load-file "~/emacs-packages/relisp/relisp.el")

  (defun enable-relisp ()
    (require 'relisp)
    (relisp-mode t))

  (add-hook 'emacs-lisp-mode-hook 'enable-relisp)
#+END_SRC

Restart emacs and relisp should be active and visible in your mode-line.

** Stability and status

Relisp is in development, and not ready for "production" use at this point.

You may clone the repo and try it out, but no promises are made about stability and correctness.
